### ISSUE TITLE
Introduce buffered versions of tensor types

### ISSUE THREAD

**Issue by jpolchlo** [geotrellis/rasterframes#19]
If we intend to allow focal operations, then we will require buffered raster types to avoid edge artifacts.  Rasterframes do not allow buffered tiles to be used, so we will need some kind of extension to the UDT framework.  We might want to provide a buffered extension to both Tile and Tensor types, but at least a buffered Tensor will be required (since we may discard simple `Tile`s in favor of the more featureful Tensor in the future).

This task interacts with the work of #18, since the operations need to be extended to handle the buffered tensor type as well.

The base case is only to read directly into a buffered tile with a known buffer size:
```scala
val df = spark.read.format("geotiff").options(Map("buffer" -> "4", ...)).load
```
But that buffer might be consumed through the chain of operations leading to a runtime error for insufficient buffering.

The "extra innings" version of this task is to read into a buffered source and then perform a logical-to-physical plan transformation step via Spark Catalyst which determines automatically the size of the buffer to read from the plan itself.  This is a significant lift, however, and will almost certainly need to wait for a later time.  This would allow us to push the read to the last minute and avoid building buffered tiles via a shuffle operation.

**Comment by echeipesh** [comment]
This is done
