### ISSUE TITLE
EO-1 Hyperion Scenes on AWS

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/rasterframes#2]
We're going to be using Hyperion as one of the hyper-spectral sources.
This issue is to find or place the scenes on a readable AWS S3 bucket so we can later read them from the cluster.

Creating a STAC catalog index for the scenes is a possible bonus objective (follow-on issue).

https://archive.usgs.gov/archive/sites/eo1.usgs.gov/hyperion_acquisition.html

Available formats from EarthExplorer:
- L1R Product in HDF format (236.0 MB) (Login Required)
- L1Gst Product in GeoTiff format (244.4 MB) (Login Required)
- L1T Product in GeoTiff format (264.6 MB) (Login Required)
- Full Resolution Browse in JPEG format (149.2 KB) (Login Required)
- GIS Ready Bundle in JPEG format + world file (150.7 KB) (Login Required)

https://www.usgs.gov/centers/eros/science/usgs-eros-archive-earth-observing-one-eo-1-hyperion?qt-science_center_objects=0#qt-science_center_objects

**Comment by moradology** [comment]
I've loaded imagery from the central valley in california here: `s3:///nasa-hyperspectral/eo1/`

**Comment by moradology** [comment]
CDL data (labels) here: https://s3.console.aws.amazon.com/s3/buckets/nasa-hyperspectral/cdl/

**Comment by jpolchlo** [comment]
@moradology  @echeipesh Can we call this closed for now?

**Comment by moradology** [comment]
Here are the EO-1 scenes we've extracted: https://s3.console.aws.amazon.com/s3/buckets/nasa-hyperspectral/eo1/?region=us-east-1&tab=overview
