### ISSUE TITLE
Consider xarray as the python backing type 

### ISSUE THREAD

**Issue by jpolchlo** [geotrellis/rasterframes#26]
We're currently using numpy arrays as the python representation of our raster cubes.  This is good in terms of the number of libraries available to manipulate that data, but given that we are expecting to work with hyperspectral data with hundreds of bands, it might be helpful to tag the bands with extra information that make it easier to interact with the data.  For example, it could be useful to label a band with its name or frequency range, and xarray is useful on this front.

I have a concern that this is a big hammer to deploy to drive in a thumb tack, so we should have a dedicated conversation about it, in case I've given short shrift to the potential of xarray.

For now, we can surely stick with numpy, so this isn't critical.

**Comment by echeipesh** [comment]
After thinking about this further, this doesn't really make sense. xarray is more of a dataframe with-in itself and doesn't map well on a single slice of data.
